### ISSUE TITLE
IE10 / IE11 Flex Problem

### ISSUE THREAD

**Issue by thexmanxyz** [insites/cookieconsent#231] opened 2017-10-15 18:31 UTC
Hey there,

I faced an issue with IE10 and IE11. I already reviewed a bit of the CSS rules and it looks like there is a issue with the flex layout. I'm not a pro in using flex but I found a easy fix which works for IE10 / IE11 and all other browsers I'm able to test (including edge, ff and chrome). I attach a screenshot which shows the browser version and also the bug I noticed. I will soon issue a pull request (#232) which fixes this issue. It's only necessary to change four lines to fix the problem. Maybe there is a better solution but this works for me. <del>I will refer to the pull request as soon as I'm done.</del> I know IE is not widely spread, I don't use it either however backward compatibility to at least this two versions should be preserved ;).

![issue-cc fw](https://user-images.githubusercontent.com/17965908/31587771-c5d87028-b1e7-11e7-8ab5-41754094a7fb.png)

**Comment by thexmanxyz** [comment] 2017-10-15 22:39
I also noticed that IE10 is still broken even with the #232 fix but I will take a look on that.

**Comment by Dolondro** [comment] 2018-07-17 12:52
Closing as duplicate of #326

**Closed by Dolondro** 2018-07-17 12:52 UTC
