### ISSUE TITLE
Internet Explorer 10/11 Button issue not fixed by version 3.0.6

### ISSUE THREAD

**Issue by AndreKoot** [insites/cookieconsent#263] opened 2018-02-25 20:26 UTC
Hi,

I tested version 3.0.6 on Internet Explorer 11 and it seems that the button issue in IE10 and IE11 is not fixed by version 3.0.6.

I have also tried the suggestions mentioned here https://github.com/insites/cookieconsent/pull/232, https://github.com/insites/cookieconsent/issues/231

Anyone got consent buttons displaying properly in IE10 and IE11?

Thank you.

André

**Comment by thexmanxyz** [comment] 2018-03-27 18:44
@AndreKoot #231 just fixed the issue for the banner layout. I already noticed that later. Which layout did you test?

**Comment by jblank1** [comment] 2018-06-26 10:32
Hello,
I wonder if there are any news on this? How can we enable the great Cookies Consent code to also work with IE versions 10 and 11?
Many thanks

**Comment by thexmanxyz** [comment] 2018-06-26 11:49
@jblank1 no news from official side but I will create an extension for all layouts. See my PR on banner layout which work for ie10  and ie11

**Comment by jblank1** [comment] 2018-06-26 14:34
@thexmanxyz - thank you so much! Sorry, am not experienced. So would I have to copy the referred CSS code prior to the one you would generate from Insites Cookies Consent?

**Comment by thexmanxyz** [comment] 2018-06-26 15:47
@jblank1 after the original code or replace the original code

**Comment by jblank1** [comment] 2018-06-26 16:04
@thexmanxyz : thank you :)

**Comment by Dolondro** [comment] 2018-07-17 12:53
Closing as duplicate of #326

**Closed by Dolondro** 2018-07-17 12:53 UTC

**Comment by thexmanxyz** [comment] 2018-08-11 18:34
@AndreKoot @jblank1 fixed with v3.1.0
