### ISSUE TITLE
mobile browsers load cc-floating instead of cc-banner

### ISSUE THREAD

**Issue by t-muir** [insites/cookieconsent#250] opened 2017-12-20 10:35 UTC
The default layout setting for position is bottom. This sets the class cc-banner when using browsers on desktops (eg  user agent Chrome - Windows)

If the user agent is changed to a mobile browser (eg Chrome Android Mobile / Safari - iPhone IOS 9) the class cc-floating is set instead of cc-banner and the default styling is broken.

**Comment by Keinbockwurst** [comment] 2018-04-06 14:32
+1

**Comment by Dolondro** [comment] 2018-07-17 15:11
Duplicate of #277

**Closed by Dolondro** 2018-07-17 15:11 UTC
