### ISSUE TITLE
Dismiss button text overflow in IE 11

### ISSUE THREAD

**Issue by webholics** [insites/cookieconsent#326] opened 2018-05-17 11:05 UTC
The text in the dismiss button overflows in IE 11 if its longer than the set `min-width: 140px` without letting the button grow as expected.

**Comment by jaegerschnitzel** [comment] 2018-05-21 15:59
Here is a screenshot of this bug: http://666kb.com/i/dtohjve0o0lklyi5y.png

**Comment by OldManBrook** [comment] 2018-05-26 00:06
I used two buttons to get around this overflow issue in IE:
```
"showLink": true,
		"theme": "classic",
		"type": "opt-in",
		"content": {
		"message": "You can choose to deny or allow use of Cookies during your visit..",
			"dismiss": '<a aria-label="deny cookies" role="button" tabindex="0" class="cc-btn cc-deny" style="min-width: 140px;">Deny</a>',
			"allow": "Allow",
			"link": "Learn More",
			"href": "/contact/privacypolicy.html",
		},
```

**Comment by karlschwaier** [comment] 2018-05-28 13:18
This issue seems to be caused by setting those buttons to flex: 1 in https://github.com/insites/cookieconsent/blob/7a493e8996faa691f47c777225ec66095fdd14d6/src/styles/layout.css#L55-L57.

I got around this with some additional CSS:

```
.cc-compliance > .cc-btn {
    flex: none !important;
}
```

**Comment by Luperi** [comment] 2018-07-06 10:09
Also fixed with: 

`.cc-compliance > .cc-btn {
    flex: 1 0 0;
}`

**Comment by Dolondro** [comment] 2018-07-17 12:55
This bug should be fixed in 3.1.0

**Closed by Dolondro** 2018-07-17 12:55 UTC

**Comment by thexmanxyz** [comment] 2018-08-11 18:33
@Dolondro Do confirm that the bug is fixed!
