### ISSUE TITLE
Revokable not showing permanently

### ISSUE THREAD

**Issue by thexmanxyz** [insites/cookieconsent#244] opened 2017-11-04 13:27 UTC
Hey there,

I noticed a strange behaviour with the small revokable button on the left side. I assume that this button should be always shown if either `opt-in` or `opt-out` is used and the banner is hidden. Or if `revokable` is set to `true` and the banner is hidden (for info mode). However the revokable button for me only shows as long as I do not refresh the site, after the decision. After that it completely disapears until cache clear. I think this is not intended or is it? It should with `revokable: true` or `opt-in` / `opt-out` always be possible to change the decision however this is only possible as long as I am not leaving the site where I made the decision. After that it's gone from all pages.

Any hints or setting changes that keeps it from permanently hiding? Or is this a bug in the API? I didn't find an issue on that problem here on Github so I'm opening a new one.

**Comment by ricovandevin** [comment] 2017-12-15 12:49
I've also noticed this issue and I agree that it is expected behavior that the revoke button is shown on every page where the banner is not shown.

**Comment by ricovandevin** [comment] 2017-12-15 13:41
This seems to be a duplicate of #177 . There is a work around in that issue.

**Comment by thexmanxyz** [comment] 2017-12-15 19:18
@ricovandevin Thanks for pointing on the issue which contains a possible fix. I will try and report back!

**Closed** 2018-07-16 15:00 UTC
