### ISSUE TITLE
Notice doesn't show if browser doesn't allow cookies

### ISSUE THREAD

**Issue by seeeeew** [insites/cookieconsent#361] opened 2018-05-25 12:07 UTC
The cookie notice doesn't seem to appear if the browser doesn't allow cookies at all. Is this behavior intended? Is there a way to disable it?

**Comment by giovanniz51** [comment] 2018-06-14 11:18
I have the same issue. Is there a fix or workaround?

**Comment by Dolondro** [comment] 2018-07-17 14:11
Duplicate of #336

**Closed by Dolondro** 2018-07-17 14:11 UTC
