### ISSUE TITLE
Add googleoff / googleon tags around content to exclude from Google index

### ISSUE THREAD

**Issue by songoo** [insites/cookieconsent#96] opened 2015-11-12 09:04 UTC
I did not expect this problem and do not know reason why google take this pop up message as more important than page content. Help please.

**Comment by songoo** [comment] 2015-11-12 09:13
Maybe its since of cookies html is inserted immediately after body, and sould be appended instead ?

I guess this part of code is responsible for placement :  

      this.element = DomBuilder.build(this.options.markup, this);
      if (!this.container.firstChild) {
        this.container.appendChild(this.element);
      } else {
        this.container.insertBefore(this.element, this.container.firstChild);
      }

not sure when condition is true so append is used instead ?

**Comment by songoo** [comment] 2015-11-12 13:14
Maybe if googleon/googleoff tags were used in generated text.

https://www.google.com/support/enterprise/static/gsa/docs/admin/70/gsa_doc_set/admin_crawl/preparing.html

**Comment by Libig** [comment] 2015-11-15 21:12
I have similar experience. Description meta tag is ignored.

**Comment by songoo** [comment] 2015-11-15 22:36
Since there is possibility to set target where cookiesconsent can be placed by script i created div at end of the body (by defaults it goes on start), and enclosed it in googleon/googleoff tag.

But that is not real solution just workaround.

**Comment by nickmz** [comment] 2016-07-26 17:41
+1
Ends up making the site look a bit amateurish when the top search result includes the cookie consent message instead of the page content.

**Comment by oliveremberton** [comment] 2016-10-12 09:37
Agreed. Can we bump this @piiupilt

**Comment by piiupilt** [comment] 2016-10-12 09:44
Already on it. It will be included in the next version.

**Comment by piiupilt** [comment] 2016-10-17 13:25
Googleoff/on tags added with #166.
Included in release [3.0.2](https://github.com/insites/cookieconsent/releases/tag/3.0.2)

**Closed by piiupilt** 2016-10-17 13:25 UTC
Labels: enhancement

**Comment by Mattia98** [comment] 2017-04-24 15:24
The problem is googleon/off doesn't work (http://stackoverflow.com/a/19489890/3832079) and this still happens
![image](https://cloud.githubusercontent.com/assets/6785428/25344571/ced2925c-2912-11e7-94a7-0c2bd054e9f7.png)

**Comment by unconnect** [comment] 2017-08-08 14:17
googleon and googleoff tag is only supported in Google Search Appliance. It's not supported in Web Search at all. In my opinion there should be an option or an default to place the div at the end of  @the body. Then move the div visually via CSS to top or bottom when the respective option is given.

**Comment by danielmarschall** [comment] 2019-05-27 19:18
Why is this closed? It is a big issue for me. I am thinking about removing cookieconsent from my page, because the Google index is spammed with the cookie disclaimer text and people don't see the actual content of my page in the search preview.

**Comment by arlogilbert** [comment] 2019-05-27 19:36
Hi @danielmarschall This was closed because the on/off was implemented. 

The initial issue was about google on off tags that only function against the legacy google search appliance, not against the general Google index.

You are welcome to fix this and submit a pull request. We are actively accepting community involvement and approving pull requests for the next tagged release. If you do decide to fix this I would recommend opening a new issue about the body append portion that was discussed in the comments.
