### ISSUE TITLE
Layout "edgeless" and position "floating right" causes display error on IE 11

### ISSUE THREAD

**Issue by nelgmo** [insites/cookieconsent#353] opened 2018-05-24 12:07 UTC
![image](https://user-images.githubusercontent.com/795917/40484408-caffd588-5f5b-11e8-89ed-e7aaf34f0f13.png)

**Comment by shaunopp** [comment] 2018-05-25 00:56
Experiencing this issue as well. Thought it was due to the fact that I was using a large amount of copy but it looks like a bug.

**Comment by Dolondro** [comment] 2018-07-17 12:52
Closing as duplicate of #326

**Closed by Dolondro** 2018-07-17 12:52 UTC
